#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.16
# In conjunction with Tcl version 8.6
#    Aug 29, 2018 07:22:47 PM EDT
#    Aug 29, 2018 07:35:45 PM EDT  platform: Windows NT
#    Aug 29, 2018 07:41:12 PM EDT  platform: Windows NT
#    Oct 06, 2018 09:25:50 PM EDT  platform: Windows NT
#    Nov 12, 2018 05:19:31 PM EST  platform: Windows NT
#    Jan 13, 2019 09:07:07 AM EST  platform: Windows NT


import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True
def set_Tk_var():
    global versionValue
    versionValue = StringVar()
    versionValue.set("w")
    global comboChipCodes
    comboChipCodes = StringVar()
    comboChipCodes.set("Normal")
    global randomChipNames
    randomChipNames = StringVar()
    randomChipNames.set("0")
    global randomVirusNames
    randomVirusNames = StringVar()
    randomVirusNames.set("0")
    global randomNavis
    randomNavis = StringVar()
    randomNavis.set("0")
    global comboElements
    comboElements = StringVar()
    comboElements.set("None")
    global comboOmegaMode
    comboOmegaMode = StringVar()
    comboOmegaMode.set("Normal")
    global randomRegMemory
    randomRegMemory = DoubleVar()
    randomRegMemory.set(0.0)
    global randomNCPShapes
    randomNCPShapes = StringVar()
    randomNCPShapes.set("0")
    global randomOutputLog
    randomOutputLog = StringVar()
    randomOutputLog.set("0")
    global comboBattlefields
    comboBattlefields = StringVar()
    comboBattlefields.set("Normal")
    global comboHellMode
    comboHellMode = StringVar()
    comboHellMode.set("Normal")
    global multChipDamage
    multChipDamage = StringVar()
    multChipDamage.set("1.0")
    global multChipVar
    multChipVar = StringVar()
    multChipVar.set("0.0")
    global multVirusHP
    multVirusHP = StringVar()
    multVirusHP.set("1.0")
    global multVirusVar
    multVirusVar = StringVar()
    multVirusVar.set("0.0")
    global versionSeed
    versionSeed = StringVar()
    global allowGMD
    allowGMD = StringVar()
    allowGMD.set("1")
    global allowBMD
    allowBMD = StringVar()
    allowBMD.set("1")
    global allowFolder
    allowFolder = StringVar()
    allowFolder.set("1")
    global allowShop
    allowShop = StringVar()
    allowShop.set("1")
    global allowChip
    allowChip = StringVar()
    allowChip.set("1")
    global allowVirus
    allowVirus = StringVar()
    allowVirus.set("1")
    global fInputPath
    fInputPath = StringVar()
    global fOutputPath
    fOutputPath = StringVar()
    global comboFolderMode
    comboFolderMode = StringVar()
    comboFolderMode.set("Normal")
    global allowDaily
    allowDaily = StringVar()
    allowDaily.set("0")
    global allowRandomObjects
    allowRandomObjects = StringVar()
    allowRandomObjects.set("0")
    global allowEasyTutorial
    allowEasyTutorial = StringVar()
    allowEasyTutorial.set("1")
    global bFillShops
    bFillShops = StringVar()
    bFillShops.set("1")
    global bIgnoreLimits
    bIgnoreLimits = StringVar()
    bIgnoreLimits.set("0")
    global allowTrades
    allowTrades = StringVar()
    allowTrades.set("1")

def buttonRandomize():
    import bn3random
    print('Randomizing...')
    optionlists = [['Normal','All-Stars','Simplified','Chaos'],['None','Enemies','Chips','Both'],['Normal','Alpha+','Beta+','Omega'],['Normal','Semi-random','Super-random'],['Normal','Hell','Insane','Death Wish'],['None','Single','Multiple','Random Single','Random Multiple']]
    codes = 0
    elems = 0
    omega = 0
    hell = 0
    fields = 0
    foldermode = 0
    if comboChipCodes.get() in optionlists[0]:
        codes = optionlists[0].index(comboChipCodes.get())
    if comboElements.get() in optionlists[1]:
        elems = optionlists[1].index(comboElements.get())
    if comboOmegaMode.get() in optionlists[2]:
        omega = optionlists[2].index(comboOmegaMode.get())
    if comboBattlefields.get() in optionlists[3]:
        fields = optionlists[3].index(comboBattlefields.get())
    if comboHellMode.get() in optionlists[4]:
        hell = optionlists[4].index(comboHellMode.get())
    if comboFolderMode.get() in optionlists[5]:
        foldermode = optionlists[5].index(comboFolderMode.get())
    bn3random.randomizerom(fInputPath.get(), fOutputPath.get(), versionValue.get(), versionSeed.get(), float(multChipDamage.get()), float(multChipVar.get()), float(multVirusHP.get()), float(multVirusVar.get()), int(codes), int(randomChipNames.get()), int(randomVirusNames.get()), int(randomNavis.get()), int(elems), int(randomRegMemory.get()), int(randomNCPShapes.get()), int(omega), int(hell), int(fields), int(foldermode), int(randomOutputLog.get()), int(allowRandomObjects.get()), int(bFillShops.get()), int(allowFolder.get()), int(allowGMD.get()), int(allowBMD.get()), int(allowShop.get()), int(allowChip.get()), int(allowVirus.get()), int(allowTrades.get()), int(allowDaily.get()), int(allowEasyTutorial.get()), int(bIgnoreLimits.get()))
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import bn3ui
    bn3ui.vp_start_gui()



















