#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.16
# In conjunction with Tcl version 8.6
#    Jan 13, 2019 09:17:29 AM EST  platform: Windows NT

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import bn3ui_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    bn3ui_support.set_Tk_var()
    top = Mega_Man_Battle_Network_3_Randomizer (root)
    bn3ui_support.init(root, top)
    root.mainloop()

w = None
def create_Mega_Man_Battle_Network_3_Randomizer(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    bn3ui_support.set_Tk_var()
    top = Mega_Man_Battle_Network_3_Randomizer (w)
    bn3ui_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Mega_Man_Battle_Network_3_Randomizer():
    global w
    w.destroy()
    w = None


class Mega_Man_Battle_Network_3_Randomizer:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font9 = "-family {Segoe UI} -size 9 -weight normal -slant "  \
            "roman -underline 0 -overstrike 0"
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("600x600+572+267")
        top.title("Mega Man Battle Network 3 Randomizer")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")



        self.Labelframe1 = LabelFrame(top)
        self.Labelframe1.place(relx=0.02, rely=0.23, relheight=0.13
                , relwidth=0.13)
        self.Labelframe1.configure(relief=GROOVE)
        self.Labelframe1.configure(foreground="black")
        self.Labelframe1.configure(text='''Version''')
        self.Labelframe1.configure(background="#d9d9d9")
        self.Labelframe1.configure(highlightbackground="#d9d9d9")
        self.Labelframe1.configure(highlightcolor="black")
        self.Labelframe1.configure(width=80)

        self.Radiobutton1 = Radiobutton(self.Labelframe1)
        self.Radiobutton1.place(relx=0.13, rely=0.24, relheight=0.33
                , relwidth=0.74, y=-12, h=6)
        self.Radiobutton1.configure(activebackground="#d9d9d9")
        self.Radiobutton1.configure(activeforeground="#000000")
        self.Radiobutton1.configure(background="#d9d9d9")
        self.Radiobutton1.configure(disabledforeground="#a3a3a3")
        self.Radiobutton1.configure(foreground="#000000")
        self.Radiobutton1.configure(highlightbackground="#d9d9d9")
        self.Radiobutton1.configure(highlightcolor="black")
        self.Radiobutton1.configure(justify=LEFT)
        self.Radiobutton1.configure(state=ACTIVE)
        self.Radiobutton1.configure(takefocus="0")
        self.Radiobutton1.configure(text='''White''')
        self.Radiobutton1.configure(value="w")
        self.Radiobutton1.configure(variable=bn3ui_support.versionValue)

        self.Radiobutton2 = Radiobutton(self.Labelframe1)
        self.Radiobutton2.place(relx=0.13, rely=0.64, relheight=0.33
                , relwidth=0.64, y=-12, h=6)
        self.Radiobutton2.configure(activebackground="#d9d9d9")
        self.Radiobutton2.configure(activeforeground="#000000")
        self.Radiobutton2.configure(background="#d9d9d9")
        self.Radiobutton2.configure(disabledforeground="#a3a3a3")
        self.Radiobutton2.configure(foreground="#000000")
        self.Radiobutton2.configure(highlightbackground="#d9d9d9")
        self.Radiobutton2.configure(highlightcolor="black")
        self.Radiobutton2.configure(justify=LEFT)
        self.Radiobutton2.configure(takefocus="0")
        self.Radiobutton2.configure(text='''Blue''')
        self.Radiobutton2.configure(value="b")
        self.Radiobutton2.configure(variable=bn3ui_support.versionValue)

        self.menubar = Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)



        self.Labelframe2 = LabelFrame(top)
        self.Labelframe2.place(relx=0.02, rely=0.9, relheight=0.09
                , relwidth=0.97)
        self.Labelframe2.configure(relief=GROOVE)
        self.Labelframe2.configure(foreground="black")
        self.Labelframe2.configure(text='''Seed''')
        self.Labelframe2.configure(background="#d9d9d9")
        self.Labelframe2.configure(highlightbackground="#d9d9d9")
        self.Labelframe2.configure(highlightcolor="black")
        self.Labelframe2.configure(width=580)

        self.Entry1 = Entry(self.Labelframe2)
        self.Entry1.place(relx=0.02, rely=0.14,height=20, relwidth=0.59)
        self.Entry1.configure(background="white")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(highlightbackground="#d9d9d9")
        self.Entry1.configure(highlightcolor="black")
        self.Entry1.configure(insertbackground="black")
        self.Entry1.configure(selectbackground="#c4c4c4")
        self.Entry1.configure(selectforeground="black")
        self.Entry1.configure(textvariable=bn3ui_support.versionSeed)
        self.Entry1.configure(validate="focusout")
        self.Entry1.configure(width=344)

        self.Button1 = Button(self.Labelframe2)
        self.Button1.place(relx=0.78, rely=0.47, height=24, width=117, y=-12
                , h=20)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(command=bn3ui_support.buttonRandomize)
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Randomize!''')

        self.Checkbutton3_1 = Checkbutton(self.Labelframe2)
        self.Checkbutton3_1.place(relx=0.62, rely=0.47, relheight=0.45
                , relwidth=0.15, y=-12, h=6)
        self.Checkbutton3_1.configure(activebackground="#d9d9d9")
        self.Checkbutton3_1.configure(activeforeground="#000000")
        self.Checkbutton3_1.configure(anchor=W)
        self.Checkbutton3_1.configure(background="#d9d9d9")
        self.Checkbutton3_1.configure(disabledforeground="#a3a3a3")
        self.Checkbutton3_1.configure(foreground="#000000")
        self.Checkbutton3_1.configure(highlightbackground="#d9d9d9")
        self.Checkbutton3_1.configure(highlightcolor="black")
        self.Checkbutton3_1.configure(justify=LEFT)
        self.Checkbutton3_1.configure(text='''Daily Run?''')
        self.Checkbutton3_1.configure(variable=bn3ui_support.allowDaily)
        self.Checkbutton3_1.configure(width=85)

        self.Labelframe3 = LabelFrame(top)
        self.Labelframe3.place(relx=0.02, rely=0.37, relheight=0.53
                , relwidth=0.97)
        self.Labelframe3.configure(relief=GROOVE)
        self.Labelframe3.configure(foreground="black")
        self.Labelframe3.configure(text='''Chip/Virus Options''')
        self.Labelframe3.configure(background="#d9d9d9")
        self.Labelframe3.configure(highlightbackground="#d9d9d9")
        self.Labelframe3.configure(highlightcolor="black")
        self.Labelframe3.configure(width=580)

        self.Entry2 = Entry(self.Labelframe3)
        self.Entry2.place(relx=0.26, rely=0.03,height=20, relwidth=0.08)
        self.Entry2.configure(background="white")
        self.Entry2.configure(disabledforeground="#a3a3a3")
        self.Entry2.configure(font="TkFixedFont")
        self.Entry2.configure(foreground="#000000")
        self.Entry2.configure(highlightbackground="#d9d9d9")
        self.Entry2.configure(highlightcolor="black")
        self.Entry2.configure(insertbackground="black")
        self.Entry2.configure(selectbackground="#c4c4c4")
        self.Entry2.configure(selectforeground="black")
        self.Entry2.configure(textvariable=bn3ui_support.multChipDamage)
        self.Entry2.configure(validate="focusout")

        self.Entry3 = Entry(self.Labelframe3)
        self.Entry3.place(relx=0.26, rely=0.13,height=20, relwidth=0.08)
        self.Entry3.configure(background="white")
        self.Entry3.configure(disabledforeground="#a3a3a3")
        self.Entry3.configure(font="TkFixedFont")
        self.Entry3.configure(foreground="#000000")
        self.Entry3.configure(highlightbackground="#d9d9d9")
        self.Entry3.configure(highlightcolor="black")
        self.Entry3.configure(insertbackground="black")
        self.Entry3.configure(selectbackground="#c4c4c4")
        self.Entry3.configure(selectforeground="black")
        self.Entry3.configure(textvariable=bn3ui_support.multChipVar)
        self.Entry3.configure(validate="focusout")

        self.Label1 = Label(self.Labelframe3)
        self.Label1.place(relx=0.02, rely=0.07, height=21, width=134, y=-12, h=20)

        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(justify=RIGHT)
        self.Label1.configure(text='''Chip Damage Multiplier''')

        self.Label2 = Label(self.Labelframe3)
        self.Label2.place(relx=0.02, rely=0.17, height=21, width=134, y=-12, h=20)

        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(justify=RIGHT)
        self.Label2.configure(text='''Chip Damage Variance''')

        self.Entry4 = Entry(self.Labelframe3)
        self.Entry4.place(relx=0.26, rely=0.23,height=20, relwidth=0.08)
        self.Entry4.configure(background="white")
        self.Entry4.configure(disabledforeground="#a3a3a3")
        self.Entry4.configure(font="TkFixedFont")
        self.Entry4.configure(foreground="#000000")
        self.Entry4.configure(highlightbackground="#d9d9d9")
        self.Entry4.configure(highlightcolor="black")
        self.Entry4.configure(insertbackground="black")
        self.Entry4.configure(selectbackground="#c4c4c4")
        self.Entry4.configure(selectforeground="black")
        self.Entry4.configure(textvariable=bn3ui_support.multVirusHP)
        self.Entry4.configure(validate="focusout")

        self.Label3 = Label(self.Labelframe3)
        self.Label3.place(relx=0.02, rely=0.26, height=21, width=134, y=-12, h=20)

        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(activeforeground="black")
        self.Label3.configure(background="#d9d9d9")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(highlightbackground="#d9d9d9")
        self.Label3.configure(highlightcolor="black")
        self.Label3.configure(justify=RIGHT)
        self.Label3.configure(text='''Enemy HP Multiplier''')

        self.Entry5 = Entry(self.Labelframe3)
        self.Entry5.place(relx=0.26, rely=0.33,height=20, relwidth=0.08)
        self.Entry5.configure(background="white")
        self.Entry5.configure(disabledforeground="#a3a3a3")
        self.Entry5.configure(font="TkFixedFont")
        self.Entry5.configure(foreground="#000000")
        self.Entry5.configure(highlightbackground="#d9d9d9")
        self.Entry5.configure(highlightcolor="black")
        self.Entry5.configure(insertbackground="black")
        self.Entry5.configure(selectbackground="#c4c4c4")
        self.Entry5.configure(selectforeground="black")
        self.Entry5.configure(textvariable=bn3ui_support.multVirusVar)

        self.Label4 = Label(self.Labelframe3)
        self.Label4.place(relx=0.02, rely=0.36, height=21, width=134, y=-12, h=20)

        self.Label4.configure(activebackground="#f9f9f9")
        self.Label4.configure(activeforeground="black")
        self.Label4.configure(background="#d9d9d9")
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(foreground="#000000")
        self.Label4.configure(highlightbackground="#d9d9d9")
        self.Label4.configure(highlightcolor="black")
        self.Label4.configure(justify=RIGHT)
        self.Label4.configure(text='''Enemy HP Variance''')

        self.TCombobox1 = ttk.Combobox(self.Labelframe3)
        self.TCombobox1.place(relx=0.64, rely=0.07, relheight=0.07, relwidth=0.33
                , y=-12, h=6)
        self.value_list = ['Normal','All-Stars','Simplified','Chaos',]
        self.TCombobox1.configure(values=self.value_list)
        self.TCombobox1.configure(textvariable=bn3ui_support.comboChipCodes)
        self.TCombobox1.configure(takefocus="")

        self.Label5 = Label(self.Labelframe3)
        self.Label5.place(relx=0.36, rely=0.07, height=21, width=154, y=-12, h=20)

        self.Label5.configure(activebackground="#f9f9f9")
        self.Label5.configure(activeforeground="black")
        self.Label5.configure(background="#d9d9d9")
        self.Label5.configure(disabledforeground="#a3a3a3")
        self.Label5.configure(foreground="#000000")
        self.Label5.configure(highlightbackground="#d9d9d9")
        self.Label5.configure(highlightcolor="black")
        self.Label5.configure(text='''Chip Code Roulette Mode''')

        self.Scale1 = Scale(self.Labelframe3)
        self.Scale1.place(relx=0.5, rely=0.42, relwidth=0.48, relheight=0.0
                , height=61)
        self.Scale1.configure(activebackground="#d9d9d9")
        self.Scale1.configure(background="#d9d9d9")
        self.Scale1.configure(font=font9)
        self.Scale1.configure(foreground="#000000")
        self.Scale1.configure(highlightbackground="#d9d9d9")
        self.Scale1.configure(highlightcolor="black")
        self.Scale1.configure(length="536")
        self.Scale1.configure(orient="horizontal")
        self.Scale1.configure(sliderlength="8")
        self.Scale1.configure(tickinterval="1.0")
        self.Scale1.configure(to="99.0")
        self.Scale1.configure(troughcolor="#d9d9d9")
        self.Scale1.configure(variable=bn3ui_support.randomRegMemory)

        self.Checkbutton3 = Checkbutton(self.Labelframe3)
        self.Checkbutton3.place(relx=0.0, rely=0.44, relheight=0.08
                , relwidth=0.35, y=-12, h=6)
        self.Checkbutton3.configure(activebackground="#d9d9d9")
        self.Checkbutton3.configure(activeforeground="#000000")
        self.Checkbutton3.configure(anchor=W)
        self.Checkbutton3.configure(background="#d9d9d9")
        self.Checkbutton3.configure(disabledforeground="#a3a3a3")
        self.Checkbutton3.configure(foreground="#000000")
        self.Checkbutton3.configure(highlightbackground="#d9d9d9")
        self.Checkbutton3.configure(highlightcolor="black")
        self.Checkbutton3.configure(justify=LEFT)
        self.Checkbutton3.configure(text='''Fill Shops''')
        self.Checkbutton3.configure(variable=bn3ui_support.bFillShops)
        self.Checkbutton3.configure(width=155)
        
        self.Checkbutton3 = Checkbutton(self.Labelframe3)
        self.Checkbutton3.place(relx=0.0, rely=0.52, relheight=0.08
                , relwidth=0.35, y=-12, h=6)
        self.Checkbutton3.configure(activebackground="#d9d9d9")
        self.Checkbutton3.configure(activeforeground="#000000")
        self.Checkbutton3.configure(anchor=W)
        self.Checkbutton3.configure(background="#d9d9d9")
        self.Checkbutton3.configure(disabledforeground="#a3a3a3")
        self.Checkbutton3.configure(foreground="#000000")
        self.Checkbutton3.configure(highlightbackground="#d9d9d9")
        self.Checkbutton3.configure(highlightcolor="black")
        self.Checkbutton3.configure(justify=LEFT)
        self.Checkbutton3.configure(text='''Free Chips in Shops''')
        self.Checkbutton3.configure(variable=bn3ui_support.bFreeShops)
        self.Checkbutton3.configure(width=155)

        self.Checkbutton3 = Checkbutton(self.Labelframe3)
        self.Checkbutton3.place(relx=0.0, rely=0.60, relheight=0.08
                , relwidth=0.35, y=-12, h=6)
        self.Checkbutton3.configure(activebackground="#d9d9d9")
        self.Checkbutton3.configure(activeforeground="#000000")
        self.Checkbutton3.configure(anchor=W)
        self.Checkbutton3.configure(background="#d9d9d9")
        self.Checkbutton3.configure(disabledforeground="#a3a3a3")
        self.Checkbutton3.configure(foreground="#000000")
        self.Checkbutton3.configure(highlightbackground="#d9d9d9")
        self.Checkbutton3.configure(highlightcolor="black")
        self.Checkbutton3.configure(justify=LEFT)
        self.Checkbutton3.configure(text='''Randomize Navis''')
        self.Checkbutton3.configure(variable=bn3ui_support.randomNavis)
        self.Checkbutton3.configure(width=155)

        self.Checkbutton1 = Checkbutton(self.Labelframe3)
        self.Checkbutton1.place(relx=0.0, rely=0.68, relheight=0.08
                , relwidth=0.35, y=-12, h=6)
        self.Checkbutton1.configure(activebackground="#d9d9d9")
        self.Checkbutton1.configure(activeforeground="#000000")
        self.Checkbutton1.configure(anchor=W)
        self.Checkbutton1.configure(background="#d9d9d9")
        self.Checkbutton1.configure(disabledforeground="#a3a3a3")
        self.Checkbutton1.configure(foreground="#000000")
        self.Checkbutton1.configure(highlightbackground="#d9d9d9")
        self.Checkbutton1.configure(highlightcolor="black")
        self.Checkbutton1.configure(justify=LEFT)
        self.Checkbutton1.configure(text='''Randomize Chip Names''')
        self.Checkbutton1.configure(variable=bn3ui_support.randomChipNames)
        self.Checkbutton1.configure(width=155)

        self.Checkbutton2 = Checkbutton(self.Labelframe3)
        self.Checkbutton2.place(relx=0.0, rely=0.76, relheight=0.08
                , relwidth=0.35, y=-12, h=6)
        self.Checkbutton2.configure(activebackground="#d9d9d9")
        self.Checkbutton2.configure(activeforeground="#000000")
        self.Checkbutton2.configure(anchor=W)
        self.Checkbutton2.configure(background="#d9d9d9")
        self.Checkbutton2.configure(disabledforeground="#a3a3a3")
        self.Checkbutton2.configure(foreground="#000000")
        self.Checkbutton2.configure(highlightbackground="#d9d9d9")
        self.Checkbutton2.configure(highlightcolor="black")
        self.Checkbutton2.configure(justify=LEFT)
        self.Checkbutton2.configure(text='''Randomize Virus Names''')
        self.Checkbutton2.configure(variable=bn3ui_support.randomVirusNames)
        self.Checkbutton2.configure(width=155)
        
        self.Checkbutton3 = Checkbutton(self.Labelframe3)
        self.Checkbutton3.place(relx=0.0, rely=0.84, relheight=0.08
                , relwidth=0.35, y=-12, h=6)
        self.Checkbutton3.configure(activebackground="#d9d9d9")
        self.Checkbutton3.configure(activeforeground="#000000")
        self.Checkbutton3.configure(anchor=W)
        self.Checkbutton3.configure(background="#d9d9d9")
        self.Checkbutton3.configure(disabledforeground="#a3a3a3")
        self.Checkbutton3.configure(foreground="#000000")
        self.Checkbutton3.configure(highlightbackground="#d9d9d9")
        self.Checkbutton3.configure(highlightcolor="black")
        self.Checkbutton3.configure(justify=LEFT)
        self.Checkbutton3.configure(text='''Normal Tutorial''')
        self.Checkbutton3.configure(variable=bn3ui_support.allowEasyTutorial)
        self.Checkbutton3.configure(width=155)
        
        self.Checkbutton3 = Checkbutton(self.Labelframe3)
        self.Checkbutton3.place(relx=0.0, rely=0.92, relheight=0.08
                , relwidth=0.35, y=-12, h=6)
        self.Checkbutton3.configure(activebackground="#d9d9d9")
        self.Checkbutton3.configure(activeforeground="#000000")
        self.Checkbutton3.configure(anchor=W)
        self.Checkbutton3.configure(background="#d9d9d9")
        self.Checkbutton3.configure(disabledforeground="#a3a3a3")
        self.Checkbutton3.configure(foreground="#000000")
        self.Checkbutton3.configure(highlightbackground="#d9d9d9")
        self.Checkbutton3.configure(highlightcolor="black")
        self.Checkbutton3.configure(justify=LEFT)
        self.Checkbutton3.configure(text='''Randomize Battle Objects''')
        self.Checkbutton3.configure(variable=bn3ui_support.allowRandomObjects)
        self.Checkbutton3.configure(width=155)

        self.TCombobox2 = ttk.Combobox(self.Labelframe3)
        self.TCombobox2.place(relx=0.64, rely=0.17, relheight=0.07, relwidth=0.33
                , y=-12, h=6)
        self.value_list = ['None','Enemies','Chips','Both',]
        self.TCombobox2.configure(values=self.value_list)
        self.TCombobox2.configure(textvariable=bn3ui_support.comboElements)
        self.TCombobox2.configure(takefocus="")

        self.Label6 = Label(self.Labelframe3)
        self.Label6.place(relx=0.36, rely=0.17, height=21, width=154, y=-12, h=20)

        self.Label6.configure(activebackground="#f9f9f9")
        self.Label6.configure(activeforeground="black")
        self.Label6.configure(background="#d9d9d9")
        self.Label6.configure(disabledforeground="#a3a3a3")
        self.Label6.configure(foreground="#000000")
        self.Label6.configure(highlightbackground="#d9d9d9")
        self.Label6.configure(highlightcolor="black")
        self.Label6.configure(text='''Randomize Elements Mode''')

        self.TCombobox3 = ttk.Combobox(self.Labelframe3)
        self.TCombobox3.place(relx=0.64, rely=0.26, relheight=0.07, relwidth=0.33
                , y=-12, h=6)
        self.value_list = ['Normal','Alpha+','Beta+','Omega',"Chaos","Chaos Alpha+","Chaos Beta+","Chaos Omega",]
        self.TCombobox3.configure(values=self.value_list)
        self.TCombobox3.configure(textvariable=bn3ui_support.comboOmegaMode)
        self.TCombobox3.configure(takefocus="")

        self.Label7 = Label(self.Labelframe3)
        self.Label7.place(relx=0.36, rely=0.26, height=21, width=154, y=-12, h=20)

        self.Label7.configure(activebackground="#f9f9f9")
        self.Label7.configure(activeforeground="black")
        self.Label7.configure(background="#d9d9d9")
        self.Label7.configure(disabledforeground="#a3a3a3")
        self.Label7.configure(foreground="#000000")
        self.Label7.configure(highlightbackground="#d9d9d9")
        self.Label7.configure(highlightcolor="black")
        self.Label7.configure(text='''Set Virus Level Mode''')

        self.Label8 = Label(self.Labelframe3)
        self.Label8.place(relx=0.285, rely=0.50, height=24, width=120, y=-12, h=20)

        self.Label8.configure(activebackground="#f9f9f9")
        self.Label8.configure(activeforeground="black")
        self.Label8.configure(background="#d9d9d9")
        self.Label8.configure(disabledforeground="#a3a3a3")
        self.Label8.configure(foreground="#000000")
        self.Label8.configure(highlightbackground="#d9d9d9")
        self.Label8.configure(highlightcolor="black")
        self.Label8.configure(text='''Randomize RegMem''')
        self.Label8.configure(width=164)

        self.Labelframe6 = LabelFrame(self.Labelframe3)
        self.Labelframe6.place(relx=0.31, rely=0.59, relheight=0.4, relwidth=0.67
                , y=-12, h=6)
        self.Labelframe6.configure(relief=GROOVE)
        self.Labelframe6.configure(foreground="black")
        self.Labelframe6.configure(text='''Allow Randomizers''')
        self.Labelframe6.configure(background="#d9d9d9")
        self.Labelframe6.configure(highlightbackground="#d9d9d9")
        self.Labelframe6.configure(highlightcolor="black")
        self.Labelframe6.configure(width=390)

        self.Checkbutton7 = Checkbutton(self.Labelframe6)
        self.Checkbutton7.place(relx=0.03, rely=0.30, relheight=0.2
                , relwidth=0.34, y=-12, h=6)
        self.Checkbutton7.configure(activebackground="#d9d9d9")
        self.Checkbutton7.configure(activeforeground="#000000")
        self.Checkbutton7.configure(background="#d9d9d9")
        self.Checkbutton7.configure(disabledforeground="#a3a3a3")
        self.Checkbutton7.configure(foreground="#000000")
        self.Checkbutton7.configure(highlightbackground="#d9d9d9")
        self.Checkbutton7.configure(highlightcolor="black")
        self.Checkbutton7.configure(justify=LEFT)
        self.Checkbutton7.configure(text='''Green Mystery Data''')
        self.Checkbutton7.configure(variable=bn3ui_support.allowGMD)

        self.Checkbutton8 = Checkbutton(self.Labelframe6)
        self.Checkbutton8.place(relx=0.03, rely=0.50, relheight=0.2
                , relwidth=0.42, y=-12, h=6)
        self.Checkbutton8.configure(activebackground="#d9d9d9")
        self.Checkbutton8.configure(activeforeground="#000000")
        self.Checkbutton8.configure(background="#d9d9d9")
        self.Checkbutton8.configure(disabledforeground="#a3a3a3")
        self.Checkbutton8.configure(foreground="#000000")
        self.Checkbutton8.configure(highlightbackground="#d9d9d9")
        self.Checkbutton8.configure(highlightcolor="black")
        self.Checkbutton8.configure(justify=LEFT)
        self.Checkbutton8.configure(text='''Blue/Purple Mystery Data''')
        self.Checkbutton8.configure(variable=bn3ui_support.allowBMD)

        self.Checkbutton6 = Checkbutton(self.Labelframe6)
        self.Checkbutton6.place(relx=0.03, rely=0.10, relheight=0.2
                , relwidth=0.36, y=-12, h=6)
        self.Checkbutton6.configure(activebackground="#d9d9d9")
        self.Checkbutton6.configure(activeforeground="#000000")
        self.Checkbutton6.configure(background="#d9d9d9")
        self.Checkbutton6.configure(disabledforeground="#a3a3a3")
        self.Checkbutton6.configure(foreground="#000000")
        self.Checkbutton6.configure(highlightbackground="#d9d9d9")
        self.Checkbutton6.configure(highlightcolor="black")
        self.Checkbutton6.configure(justify=LEFT)
        self.Checkbutton6.configure(text='''Starting/Extra Folders''')
        self.Checkbutton6.configure(variable=bn3ui_support.allowFolder)

        self.Checkbutton9 = Checkbutton(self.Labelframe6)
        self.Checkbutton9.place(relx=0.54, rely=0.10, relheight=0.2
                , relwidth=0.37, y=-12, h=6)
        self.Checkbutton9.configure(activebackground="#d9d9d9")
        self.Checkbutton9.configure(activeforeground="#000000")
        self.Checkbutton9.configure(background="#d9d9d9")
        self.Checkbutton9.configure(disabledforeground="#a3a3a3")
        self.Checkbutton9.configure(foreground="#000000")
        self.Checkbutton9.configure(highlightbackground="#d9d9d9")
        self.Checkbutton9.configure(highlightcolor="black")
        self.Checkbutton9.configure(justify=LEFT)
        self.Checkbutton9.configure(text='''Shops/Number Trader''')
        self.Checkbutton9.configure(variable=bn3ui_support.allowShop)

        self.Checkbutton10 = Checkbutton(self.Labelframe6)
        self.Checkbutton10.place(relx=0.54, rely=0.30, relheight=0.2
                , relwidth=0.29, y=-12, h=6)
        self.Checkbutton10.configure(activebackground="#d9d9d9")
        self.Checkbutton10.configure(activeforeground="#000000")
        self.Checkbutton10.configure(background="#d9d9d9")
        self.Checkbutton10.configure(disabledforeground="#a3a3a3")
        self.Checkbutton10.configure(foreground="#000000")
        self.Checkbutton10.configure(highlightbackground="#d9d9d9")
        self.Checkbutton10.configure(highlightcolor="black")
        self.Checkbutton10.configure(justify=LEFT)
        self.Checkbutton10.configure(text='''Battle Chip Data''')
        self.Checkbutton10.configure(variable=bn3ui_support.allowChip)

        self.Checkbutton11 = Checkbutton(self.Labelframe6)
        self.Checkbutton11.place(relx=0.54, rely=0.50, relheight=0.2
                , relwidth=0.43, y=-12, h=6)
        self.Checkbutton11.configure(activebackground="#d9d9d9")
        self.Checkbutton11.configure(activeforeground="#000000")
        self.Checkbutton11.configure(background="#d9d9d9")
        self.Checkbutton11.configure(disabledforeground="#a3a3a3")
        self.Checkbutton11.configure(foreground="#000000")
        self.Checkbutton11.configure(highlightbackground="#d9d9d9")
        self.Checkbutton11.configure(highlightcolor="black")
        self.Checkbutton11.configure(justify=LEFT)
        self.Checkbutton11.configure(text='''Navis/Viruses/Battle Drops''')
        self.Checkbutton11.configure(variable=bn3ui_support.allowVirus)
        
        self.Checkbutton12 = Checkbutton(self.Labelframe6)
        self.Checkbutton12.place(relx=0.03, rely=0.70, relheight=0.2
                , relwidth=0.30, y=-12, h=6)
        self.Checkbutton12.configure(activebackground="#d9d9d9")
        self.Checkbutton12.configure(activeforeground="#000000")
        self.Checkbutton12.configure(background="#d9d9d9")
        self.Checkbutton12.configure(disabledforeground="#a3a3a3")
        self.Checkbutton12.configure(foreground="#000000")
        self.Checkbutton12.configure(highlightbackground="#d9d9d9")
        self.Checkbutton12.configure(highlightcolor="black")
        self.Checkbutton12.configure(justify=LEFT)
        self.Checkbutton12.configure(text='''NPC Chip Trades''')
        self.Checkbutton12.configure(variable=bn3ui_support.allowTrades)

        self.Label7_1 = Label(self.Labelframe3)
        self.Label7_1.place(relx=0.36, rely=0.36, height=21, width=154, y=-12
                , h=20)
        self.Label7_1.configure(activebackground="#f9f9f9")
        self.Label7_1.configure(activeforeground="black")
        self.Label7_1.configure(background="#d9d9d9")
        self.Label7_1.configure(disabledforeground="#a3a3a3")
        self.Label7_1.configure(foreground="#000000")
        self.Label7_1.configure(highlightbackground="#d9d9d9")
        self.Label7_1.configure(highlightcolor="black")
        self.Label7_1.configure(text='''Set Folder Lock Mode''')

        self.TCombobox3_2 = ttk.Combobox(self.Labelframe3)
        self.TCombobox3_2.place(relx=0.64, rely=0.36, relheight=0.07
                , relwidth=0.33, y=-12, h=6)
        self.value_list = ['None','Preset Single','Preset Multiple','Random Single','Random Multiple']
        self.TCombobox3_2.configure(values=self.value_list)
        self.TCombobox3_2.configure(textvariable=bn3ui_support.comboFolderMode)
        self.TCombobox3_2.configure(takefocus="")

        self.Labelframe4 = LabelFrame(top)
        self.Labelframe4.place(relx=0.17, rely=0.23, relheight=0.13
                , relwidth=0.82)
        self.Labelframe4.configure(relief=GROOVE)
        self.Labelframe4.configure(foreground="black")
        self.Labelframe4.configure(text='''Other Options''')
        self.Labelframe4.configure(background="#d9d9d9")
        self.Labelframe4.configure(highlightbackground="#d9d9d9")
        self.Labelframe4.configure(highlightcolor="black")
        self.Labelframe4.configure(width=490)

        self.Checkbutton4 = Checkbutton(self.Labelframe4)
        self.Checkbutton4.place(relx=0.000, rely=0.14, relheight=0.32
                , relwidth=0.35, y=-12, h=6)
        self.Checkbutton4.configure(activebackground="#d9d9d9")
        self.Checkbutton4.configure(activeforeground="#000000")
        self.Checkbutton4.configure(background="#d9d9d9")
        self.Checkbutton4.configure(disabledforeground="#a3a3a3")
        self.Checkbutton4.configure(foreground="#000000")
        self.Checkbutton4.configure(highlightbackground="#d9d9d9")
        self.Checkbutton4.configure(highlightcolor="black")
        self.Checkbutton4.configure(justify=LEFT)
        self.Checkbutton4.configure(text='''Randomize NCP Shapes''')
        self.Checkbutton4.configure(variable=bn3ui_support.randomNCPShapes)

        self.Checkbutton5 = Checkbutton(self.Labelframe4)
        self.Checkbutton5.place(relx=0.019, rely=0.46, relheight=0.32
                , relwidth=0.35, y=-12, h=6)
        self.Checkbutton5.configure(activebackground="#d9d9d9")
        self.Checkbutton5.configure(activeforeground="#000000")
        self.Checkbutton5.configure(background="#d9d9d9")
        self.Checkbutton5.configure(disabledforeground="#a3a3a3")
        self.Checkbutton5.configure(foreground="#000000")
        self.Checkbutton5.configure(highlightbackground="#d9d9d9")
        self.Checkbutton5.configure(highlightcolor="black")
        self.Checkbutton5.configure(justify=LEFT)
        self.Checkbutton5.configure(text='''Enable Detailed Output Log''')
        self.Checkbutton5.configure(variable=bn3ui_support.randomOutputLog)
        
        self.Checkbutton6 = Checkbutton(self.Labelframe4)
        self.Checkbutton6.place(relx=0.02, rely=0.78, relheight=0.32
                , relwidth=0.35, y=-12, h=6)
        self.Checkbutton6.configure(activebackground="#d9d9d9")
        self.Checkbutton6.configure(activeforeground="#000000")
        self.Checkbutton6.configure(background="#d9d9d9")
        self.Checkbutton6.configure(disabledforeground="#a3a3a3")
        self.Checkbutton6.configure(foreground="#000000")
        self.Checkbutton6.configure(highlightbackground="#d9d9d9")
        self.Checkbutton6.configure(highlightcolor="black")
        self.Checkbutton6.configure(justify=LEFT)
        self.Checkbutton6.configure(text='''Ignore HP/Damage Limiters''')
        self.Checkbutton6.configure(variable=bn3ui_support.bIgnoreLimits)

        self.TCombobox4 = ttk.Combobox(self.Labelframe4)
        self.TCombobox4.place(relx=0.78, rely=0.20, relheight=0.27, relwidth=0.19
                , y=-12, h=6)
        self.value_list = ['Normal','Semi-random','Super-random',]
        self.TCombobox4.configure(values=self.value_list)
        self.TCombobox4.configure(textvariable=bn3ui_support.comboBattlefields)
        self.TCombobox4.configure(takefocus="")

        self.Label9 = Label(self.Labelframe4)
        self.Label9.place(relx=0.51, rely=0.24, height=21, width=124, y=-12, h=20)

        self.Label9.configure(activebackground="#f9f9f9")
        self.Label9.configure(activeforeground="black")
        self.Label9.configure(background="#d9d9d9")
        self.Label9.configure(disabledforeground="#a3a3a3")
        self.Label9.configure(foreground="#000000")
        self.Label9.configure(highlightbackground="#d9d9d9")
        self.Label9.configure(highlightcolor="black")
        self.Label9.configure(text='''Randomize Battlefields''')

        self.TCombobox4_1 = ttk.Combobox(self.Labelframe4)
        self.TCombobox4_1.place(relx=0.78, rely=0.64, relheight=0.27
                , relwidth=0.19, y=-12, h=6)
        self.value_list = ['Normal','Hell','Insane','Death Wish',]
        self.TCombobox4_1.configure(values=self.value_list)
        self.TCombobox4_1.configure(textvariable=bn3ui_support.comboHellMode)
        self.TCombobox4_1.configure(takefocus="")

        self.Label10 = Label(self.Labelframe4)
        self.Label10.place(relx=0.51, rely=0.68, height=21, width=124, y=-12
                , h=20)
        self.Label10.configure(activebackground="#f9f9f9")
        self.Label10.configure(activeforeground="black")
        self.Label10.configure(background="#d9d9d9")
        self.Label10.configure(disabledforeground="#a3a3a3")
        self.Label10.configure(foreground="#000000")
        self.Label10.configure(highlightbackground="#d9d9d9")
        self.Label10.configure(highlightcolor="black")
        self.Label10.configure(text='''Enable Hell Mode''')

        self.Labelframe5 = LabelFrame(top)
        self.Labelframe5.place(relx=0.02, rely=0.08, relheight=0.14
                , relwidth=0.97)
        self.Labelframe5.configure(relief=GROOVE)
        self.Labelframe5.configure(foreground="black")
        self.Labelframe5.configure(text='''Filepaths''')
        self.Labelframe5.configure(background="#d9d9d9")
        self.Labelframe5.configure(highlightbackground="#d9d9d9")
        self.Labelframe5.configure(highlightcolor="black")
        self.Labelframe5.configure(width=580)

        self.Entry6 = Entry(self.Labelframe5)
        self.Entry6.place(relx=0.14, rely=0.14,height=20, relwidth=0.85)
        self.Entry6.configure(background="white")
        self.Entry6.configure(disabledforeground="#a3a3a3")
        self.Entry6.configure(font="TkFixedFont")
        self.Entry6.configure(foreground="#000000")
        self.Entry6.configure(highlightbackground="#d9d9d9")
        self.Entry6.configure(highlightcolor="black")
        self.Entry6.configure(insertbackground="black")
        self.Entry6.configure(selectbackground="#c4c4c4")
        self.Entry6.configure(selectforeground="black")
        self.Entry6.configure(textvariable=bn3ui_support.fInputPath)

        self.Entry7 = Entry(self.Labelframe5)
        self.Entry7.place(relx=0.14, rely=0.55,height=20, relwidth=0.85)
        self.Entry7.configure(background="white")
        self.Entry7.configure(disabledforeground="#a3a3a3")
        self.Entry7.configure(font="TkFixedFont")
        self.Entry7.configure(foreground="#000000")
        self.Entry7.configure(highlightbackground="#d9d9d9")
        self.Entry7.configure(highlightcolor="black")
        self.Entry7.configure(insertbackground="black")
        self.Entry7.configure(selectbackground="#c4c4c4")
        self.Entry7.configure(selectforeground="black")
        self.Entry7.configure(textvariable=bn3ui_support.fOutputPath)

        self.Label11 = Label(self.Labelframe5)
        self.Label11.place(relx=0.02, rely=0.27, height=21, width=65, y=-10, h=21)

        self.Label11.configure(activebackground="#f9f9f9")
        self.Label11.configure(activeforeground="black")
        self.Label11.configure(background="#d9d9d9")
        self.Label11.configure(disabledforeground="#a3a3a3")
        self.Label11.configure(foreground="#000000")
        self.Label11.configure(highlightbackground="#d9d9d9")
        self.Label11.configure(highlightcolor="black")
        self.Label11.configure(text='''Input File''')

        self.Label12 = Label(self.Labelframe5)
        self.Label12.place(relx=0.02, rely=0.68, height=21, width=64, y=-10, h=21)

        self.Label12.configure(activebackground="#f9f9f9")
        self.Label12.configure(activeforeground="black")
        self.Label12.configure(background="#d9d9d9")
        self.Label12.configure(disabledforeground="#a3a3a3")
        self.Label12.configure(foreground="#000000")
        self.Label12.configure(highlightbackground="#d9d9d9")
        self.Label12.configure(highlightcolor="black")
        self.Label12.configure(text='''Output File''')

        self.Message1 = Message(top)
        self.Message1.place(relx=0.02, rely=0.02, relheight=0.06, relwidth=0.97)
        self.Message1.configure(background="#d9d9d9")
        self.Message1.configure(foreground="#000000")
        self.Message1.configure(highlightbackground="#d9d9d9")
        self.Message1.configure(highlightcolor="black")
        self.Message1.configure(text='''Originally created by Samfin/Mountebank, with features added by X Kirby. Created using Python, PAGE, and PyInstaller. Executable icon found posted on the /r/BattleNetwork subreddit.''')
        self.Message1.configure(width=580)






if __name__ == '__main__':
    vp_start_gui()



